sonar.projectKey=Halcyora_Github-Actions
sonar.organization=halcyora
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/.venv/**